import Head from 'next/head'
import Image from 'next/image'
import { useReducer, useState, useRef } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const patientRef = useRef();
  const [state, dispatch] = useReducer(reducer, { patient: [] })
  function reducer(state, action){
    switch (action.type){
      case 'ADD_PATIENT':
        const newPatient = {
          id: action.id,
          name: action.name,
        }
        return {
          patient : [ ...state.patient, newPatient ]
        }
        case 'REMOVE_PATIENT':
          const remaining = state.patient.filter(patient => patient.id != action.id);
        return {
          patient : remaining
        }
    }
  }

  const handleSubmit = (e) =>{
    e.preventDefault();
    dispatch({type: 'ADD_PATIENT', name: patientRef.current.value, id: state.patient.length + 1})
    patientRef.current.value = ''
  }

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <h1>Counter with useReducer</h1>
        <div>
          <h2>Count : {state.count}</h2>
        </div>
        <div style={{display: 'flex'}}>
          <button onClick={()=> dispatch({type: 'INCREMENT'})}>+</button>
          <button onClick={()=> dispatch({type: 'DECREMENT'})}>-</button>
        </div> */}
       <br />
       <h1>Add Patient</h1>
        <form onSubmit={handleSubmit}>
          <input style={{borderRadius: '5px', borderColor: 'green'}} type="text" ref={patientRef} />
        </form>
        <h2>Total Patient : {state.patient.length}</h2>
        <ul>
          {
              state.patient.map(p => <li onClick={()=> dispatch({type: 'REMOVE_PATIENT', id: p.id})} key={p.id} style={{listStyle:'none'}}>{p.name}</li>)
          }
        </ul>
      </main>
    </div>
  )
}
